// ---------------------------------------------------------------------------
// State chain tests: Doorstop-faithful fingerprints + per-item state chips.
//
// Fingerprint fidelity is pinned three ways:
//   1. Fixture vectors — src/doorstop-state.fixtures.json was generated by
//      running REAL Doorstop (notes/fixture-generator.py) over a small
//      workspace; every item's `stamp()` and `stamp(links=True)` are asserted
//      byte-for-byte against the port for BOTH includeLinks variants.
//   2. Doorstop's own unit vectors (doorstop/core/tests/test_item.py) are
//      embedded below for the extended-reviewed-attribute serialization and
//      the base empty item.
//   3. Standard SHA-256 test vectors pin the hand-rolled hasher.
//
// Chip semantics are asserted against the fixture's captured Doorstop
// validator issues: every plugin finding of a mapped class must agree with
// Doorstop's emitted severity (INFO/WARNING/ERROR), and every captured
// Doorstop issue (except the unmodeled "no text") must have a matching
// plugin finding — the "severity model is pinned by fixture tests" clause of
// the contract (§6/§9).  The synthetic scenarios additionally cover the
// parent-stamp-changed → child-suspect flow and the childrenByUid scoping.
// ---------------------------------------------------------------------------

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import type {
  DoorstopDocumentConfig,
  DoorstopIndex,
  DoorstopItemReference,
  DoorstopStampableItem,
  Finding,
  ItemRecord,
  LinkRecord,
} from "./doorstop-contract.js";
import {
  buildDoorstopIndex,
  parseDoorstopItem,
} from "./doorstop-model.js";
import {
  computeItemStamp,
  computeItemStates,
  doorstopConvertToStr,
  pyStringRepr,
  sortLinkRecords,
  splitDoorstopUid,
  stampFromFingerprintParts,
} from "./doorstop-state.js";
import { makeDocument, makeItem } from "./test-fixtures.js";

// --- fixture loading -----------------------------------------------------------

interface FixtureReference {
  type: "file";
  path: string;
  keyword?: string;
  sha?: string;
}

interface FixtureIssue {
  severity: "INFO" | "WARNING" | "ERROR";
  message: string;
}

interface FixtureItem {
  uid: string;
  documentPrefix: string;
  path: string;
  level: string;
  active: boolean;
  derived: boolean;
  normative: boolean;
  header: string;
  text: string;
  ref: string;
  references: FixtureReference[] | null;
  links: LinkRecord[];
  attributes: Record<string, unknown>;
  reviewed: string | null;
  stamp: string;
  reviewStamp: string;
  yaml: string;
  issues: FixtureIssue[];
}

interface FixtureDocument {
  directoryPath: string;
  configPath: string;
  prefix: string;
  digits: number;
  separator: string;
  parentPrefix: string | null;
  itemformat: string;
  reviewedAttributes: string[];
}

interface FixtureSchemaGap {
  key: string;
  scalar: string;
  parity: "equal" | "divergent";
  doorstopConvert: string;
  doorstopStamp: string;
}

interface FixtureFile {
  generator: { doorstopVersion: string; doorstopSource: string };
  documents: FixtureDocument[];
  items: FixtureItem[];
  schemaGap: FixtureSchemaGap[];
  knownFilePaths: string[];
}

const fixtures = JSON.parse(
  readFileSync(new URL("./doorstop-state.fixtures.json", import.meta.url), "utf8"),
) as FixtureFile;

/** Contract-shaped document configs from the fixture documents. */
function fixtureConfigs(): DoorstopDocumentConfig[] {
  return fixtures.documents.map((doc) => ({
    directoryPath: doc.directoryPath,
    configPath: doc.configPath,
    prefix: doc.prefix,
    digits: doc.digits,
    separator: doc.separator,
    ...(doc.parentPrefix === null ? {} : { parentPrefix: doc.parentPrefix }),
    itemformat: doc.itemformat as DoorstopDocumentConfig["itemformat"],
    extra: {
      ...(doc.reviewedAttributes.length > 0
        ? { attributes: { reviewed: doc.reviewedAttributes } }
        : {}),
    },
  }));
}

function referencesOf(fixture: FixtureItem): DoorstopItemReference[] | undefined {
  if (fixture.references === null) return undefined;
  return fixture.references.map((reference) => {
    const out: DoorstopItemReference = { type: "file", path: reference.path };
    if (reference.keyword !== undefined) out.keyword = reference.keyword;
    if (reference.sha !== undefined) out.sha = reference.sha;
    return out;
  });
}

/** ItemRecord matching what the model chain would produce for the fixture. */
function itemRecordOf(fixture: FixtureItem): ItemRecord {
  const record: ItemRecord = {
    uid: fixture.uid,
    documentPrefix: fixture.documentPrefix,
    path: fixture.path,
    level: fixture.level,
    active: fixture.active,
    derived: fixture.derived,
    normative: fixture.normative,
    text: fixture.text,
    ref: fixture.ref,
    links: fixture.links.map((link) => ({ uid: link.uid, fingerprint: link.fingerprint })),
    attributes: fixture.attributes,
    reviewed: fixture.reviewed,
    raw: { yaml: fixture.yaml },
    stateKeys: [],
  };
  if (fixture.header !== "") record.header = fixture.header;
  const references = referencesOf(fixture);
  if (references !== undefined) record.references = references;
  return record;
}

/** The DoorstopStampableItem for a fixture item (byte-fidelity test input). */
function stampableOf(fixture: FixtureItem): DoorstopStampableItem {
  return {
    uid: fixture.uid,
    text: fixture.text,
    ref: fixture.ref,
    ...(fixture.references === null ? {} : { references: referencesOf(fixture)! }),
    links: fixture.links.map((link) => ({ uid: link.uid, fingerprint: link.fingerprint })),
    attributes: fixture.attributes,
  };
}

/** Full plugin-style index assembled from the fixtures (the shape the model
 *  chain produces; `buildDoorstopIndex` itself is exercised separately). */
function buildIndexFromFixtures(): DoorstopIndex {
  const documents = fixtureConfigs();
  const items = fixtures.items.map(itemRecordOf);
  const byUid = new Map(items.map((item) => [item.uid, item]));
  const byPrefix = new Map(documents.map((document) => [document.prefix, document]));
  const childrenByUid = new Map<string, ItemRecord[]>();
  for (const item of items) {
    for (const link of item.links) {
      const target = byUid.get(link.uid);
      if (target === undefined) continue;
      const children = childrenByUid.get(link.uid);
      if (children !== undefined) {
        children.push(item);
      } else {
        childrenByUid.set(link.uid, [item]);
      }
    }
  }
  return {
    documents,
    items,
    byUid,
    byPrefix,
    parentLinksByUid: new Map(items.map((item) => [item.uid, item.links])),
    childrenByUid,
    findings: [],
    ok: true,
    diagnostics: [],
    knownFilePaths: new Set(fixtures.knownFilePaths),
    counts: {
      suspectLinks: 0,
      unreviewedChanges: 0,
      unknownLinks: 0,
      missingReferences: 0,
      items: items.length,
      documents: documents.length,
    },
  };
}

const itemsByUid = new Map(fixtures.items.map((item) => [item.uid, item]));
const configsByPrefix = new Map(fixtureConfigs().map((config) => [config.prefix, config]));

function configOf(fixture: FixtureItem): DoorstopDocumentConfig {
  const config = configsByPrefix.get(fixture.documentPrefix);
  if (config === undefined) throw new Error(`no fixture config for ${fixture.documentPrefix}`);
  return config;
}

/** A document config with the reviewed attribute list; used by the embedded
 *  Doorstop unit-vector tests. */
function reviewedConfig(names: string[], extra: Record<string, unknown> = {}): DoorstopDocumentConfig {
  return {
    directoryPath: "",
    configPath: "",
    prefix: "RQ",
    digits: 3,
    separator: "",
    itemformat: "yaml",
    extra: {
      attributes: { reviewed: names },
      ...extra,
    },
  };
}

function baseStampable(attributes: Record<string, unknown> = {}): DoorstopStampableItem {
  return {
    uid: "RQ001",
    text: "",
    ref: "",
    links: [],
    attributes: attributes as Record<string, unknown>,
  };
}

// --- SHA-256 / base64 vectors ---------------------------------------------------

describe("stampFromFingerprintParts — SHA-256 → URL-safe Base64", () => {
  it("matches the standard SHA-256 test vectors (empty, abc, proverb)", () => {
    expect(stampFromFingerprintParts([""])).toBe("47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU=");
    expect(stampFromFingerprintParts(["abc"])).toBe("ungWv48Bz-pBQUDeXa4iI7ADYaOWF3qctBD_YfIAFa0=");
    expect(stampFromFingerprintParts(["The quick brown fox jumps over the lazy dog"])).toBe(
      "16j7swfXgJRpypq8sAguT41WUeRtPNt2LQLQvzfJ5ZI=",
    );
  });

  it("concatenates parts with no separator (Doorstop Stamp.digest)", () => {
    expect(stampFromFingerprintParts(["RQ001"])).toBe("OoHOpBnrt8us7ph8DVnz5KrQs6UBqj_8MEACA0gWpjY=");
    expect(stampFromFingerprintParts(["RQ", "001"])).toBe(
      stampFromFingerprintParts(["RQ001"]),
    );
  });

  it("uses the URL-safe alphabet with padding (Python urlsafe_b64encode)", () => {
    const stamp = stampFromFingerprintParts(["abc"]);
    expect(stamp).toMatch(/^[A-Za-z0-9_-]+=*$/);
    expect(stamp.endsWith("=")).toBe(true);
  });
});

describe("python serialization helpers", () => {
  it("reproduces Doorstop _convert_to_str byte-for-byte", () => {
    expect(doorstopConvertToStr("q\\w")).toBe("\\T<class 'str'>\\Vq\\\\w");
    expect(doorstopConvertToStr(1)).toBe("\\T<class 'int'>\\V1");
    expect(doorstopConvertToStr(null)).toBe("\\T<class 'NoneType'>\\VNone");
    expect(doorstopConvertToStr(["a", "b", ["c", { d: "e", f: ["g"] }]])).toBe(
      "\\L\\T<class 'str'>\\Va\\T<class 'str'>\\Vb\\L\\T<class 'str'>\\Vc" +
        "\\D\\T<class 'str'>\\Ve\\L\\T<class 'str'>\\Vg",
    );
    // dict keys sorted, only values serialized (Doorstop sorted(value.keys()))
    expect(doorstopConvertToStr({ z: 1, a: [true, null] })).toBe(
      "\\D\\L\\T<class 'bool'>\\VTrue\\T<class 'NoneType'>\\VNone\\T<class 'int'>\\V1",
    );
  });

  it("reproduces Python str() of the references list (repr quoting)", () => {
    // a value containing a single quote but no double quote uses double quotes
    // (Python repr), backslashes are doubled
    expect(
      pyStringRepr("x y'z"),
    ).toBe('"x y\'z"');
    expect(
      pyStringRepr("a\\b"),
    ).toBe("'a\\\\b'");
  });

  it("escapes non-ASCII non-printable code points like Python 3 repr", () => {
    // C1 control, NBSP (Zs), line separator (Zl), BOM and zero-width space
    // (Cf), DEL — Python repr escapes all of these (verified in the fixture
    // venv); the previous port passed them through raw and diverged from
    // `Stamp.digest` for text/ref/attribute values holding them
    expect(pyStringRepr("\x85")).toBe("'\\x85'");
    expect(pyStringRepr("\xa0")).toBe("'\\xa0'");
    expect(pyStringRepr("\u2028")).toBe("'\\u2028'");
    expect(pyStringRepr("\ufeff")).toBe("'\\ufeff'");
    expect(pyStringRepr("\u200b")).toBe("'\\u200b'");
    expect(pyStringRepr("\x7f")).toBe("'\\x7f'");
    // printable non-ASCII — including the supplementary plane and C1-free
    // Latin-1 — passes through raw, exactly like Python 3 repr
    expect(pyStringRepr("café \u{1f600}")).toBe("'café \u{1f600}'");
  });

  it("serializes non-finite numbers and YAML timestamps with Python spellings", () => {
    // js-yaml maps `.nan`/`.inf`/`-.inf` onto JS NaN/±Infinity; Python str()
    // spells them lowercase
    expect(doorstopConvertToStr(NaN)).toBe("\\T<class 'float'>\\Vnan");
    expect(doorstopConvertToStr(Infinity)).toBe("\\T<class 'float'>\\Vinf");
    expect(doorstopConvertToStr(-Infinity)).toBe("\\T<class 'float'>\\V-inf");
    // js-yaml parses YAML timestamps as JS Dates; midnight-UTC Dates render
    // as Python datetime.date, others as a UTC datetime (str() forms)
    expect(doorstopConvertToStr(new Date("2024-01-01T00:00:00.000Z"))).toBe(
      "\\T<class 'datetime.date'>\\V2024-01-01",
    );
    expect(doorstopConvertToStr(new Date("2024-01-01T12:34:56.000Z"))).toBe(
      "\\T<class 'datetime.datetime'>\\V2024-01-01 12:34:56+00:00",
    );
  });
});

describe("Doorstop UID parsing and link sorting", () => {
  it("ports UID.split_uid (prefix/number/name; DOCTEST vectors)", () => {
    expect(splitDoorstopUid("ABC00123")).toEqual({ prefix: "ABC", number: 123, name: "" });
    expect(splitDoorstopUid("ABC.HLR_01-00123")).toEqual({ prefix: "ABC.HLR_01", number: 123, name: "" });
    expect(splitDoorstopUid("REQ2-001")).toEqual({ prefix: "REQ2", number: 1, name: "" });
    expect(splitDoorstopUid("REQ2-NAME")).toEqual({ prefix: "REQ2", number: -1, name: "NAME" });
    expect(splitDoorstopUid("REQ2-123NAME")).toEqual({ prefix: "REQ2", number: -1, name: "123NAME" });
    expect(splitDoorstopUid("REQ001")).toEqual({ prefix: "REQ", number: 1, name: "" });
  });

  it("sorts links like Doorstop's sorted UID set (numeric part, then prefix)", () => {
    const records = (uids: string[]): LinkRecord[] => uids.map((uid) => ({ uid, fingerprint: null }));
    expect(sortLinkRecords(records(["REQ010", "REQ002", "REQ001"])).map((l) => l.uid)).toEqual([
      "REQ001",
      "REQ002",
      "REQ010",
    ]);
    // cross-prefix: lowercased prefix, then numeric part
    expect(sortLinkRecords(records(["TST001", "REQ005", "fAb002"])).map((l) => l.uid)).toEqual([
      "fAb002",
      "REQ005",
      "TST001",
    ]);
  });

  it("matches Python re.match prefix semantics — trailing junk is ignored", () => {
    // Python `re.match` is end-UNANCHORED (types.py split_uid, verified in
    // the fixture venv): "REQ001foo" parses as (REQ, 1) via the second
    // regex with the trailing junk ignored — the previous anchored port
    // returned null and fell back to raw-string comparison
    expect(splitDoorstopUid("REQ001foo")).toEqual({ prefix: "REQ", number: 1, name: "" });
    expect(splitDoorstopUid("ABC00123xyz")).toEqual({ prefix: "ABC", number: 123, name: "" });
  });

  it("parses the numeric part with Python int() semantics (base-10 only)", () => {
    // Python int() rejects these in base 10 → NAMES (verified in the fixture
    // venv); the previous Number() coercion read them as 16 / 100
    expect(splitDoorstopUid("REQ-0x10")).toEqual({ prefix: "REQ", number: -1, name: "0x10" });
    expect(splitDoorstopUid("REQ-1e2")).toEqual({ prefix: "REQ", number: -1, name: "1e2" });
    expect(splitDoorstopUid("REQ-001xyz")).toEqual({ prefix: "REQ", number: -1, name: "001xyz" });
  });

  it("keeps ties on case-variant equal UIDs stable (input order)", () => {
    // Doorstop UID.__lt__: equal case-insensitive prefixes + numbers compare
    // the name ("" == "") → a tie; JS Array.prototype.sort is stable, like
    // Python's sorted()
    const records = (uids: string[]): LinkRecord[] => uids.map((uid) => ({ uid, fingerprint: null }));
    expect(sortLinkRecords(records(["REQ001", "req001"])).map((l) => l.uid)).toEqual([
      "REQ001",
      "req001",
    ]);
    expect(sortLinkRecords(records(["req001", "REQ001"])).map((l) => l.uid)).toEqual([
      "req001",
      "REQ001",
    ]);
  });
});

// --- fixture-driven byte fidelity ------------------------------------------------

describe("computeItemStamp — byte fidelity against REAL Doorstop fixtures", () => {
  it("imports fixtures generated with real Doorstop", () => {
    expect(fixtures.generator.doorstopVersion).toBe("3.2");
    expect(fixtures.generator.doorstopSource).toMatch(/doorstop-dev\/doorstop commit/);
    expect(fixtures.items.length).toBeGreaterThanOrEqual(14);
    // the schema-gap block pins REAL Doorstop serializations for extended
    // reviewed attributes at the YAML 1.1/1.2 typing boundary
    expect(fixtures.schemaGap.length).toBeGreaterThanOrEqual(12);
  });

  it("reproduces every item's link-record stamp (includeLinks: false)", () => {
    for (const fixture of fixtures.items) {
      expect(computeItemStamp(stampableOf(fixture), configOf(fixture), false), fixture.uid).toBe(
        fixture.stamp,
      );
    }
  });

  it("reproduces every item's review stamp (includeLinks default true and explicit)", () => {
    for (const fixture of fixtures.items) {
      expect(computeItemStamp(stampableOf(fixture), configOf(fixture)), fixture.uid).toBe(
        fixture.reviewStamp,
      );
      expect(computeItemStamp(stampableOf(fixture), configOf(fixture), true), fixture.uid).toBe(
        fixture.reviewStamp,
      );
    }
  });

  it("keeps both stamp variants on one implementation (no divergent serialization)", () => {
    // review stamp = link-record stamp + sorted link UID parts
    const re003 = itemsByUid.get("REQ003")!;
    const withLinks = computeItemStamp(
      { ...stampableOf(re003), links: [] },
      configOf(re003),
      true,
    );
    expect(withLinks).toBe(computeItemStamp({ ...stampableOf(re003), links: [] }, configOf(re003), false));
  });

  it("does not include an empty references list (Doorstop: `if self.references:`)", () => {
    const emptyRefs: DoorstopStampableItem = {
      ...baseStampable(),
      references: [],
    };
    expect(
      computeItemStamp(emptyRefs, reviewedConfig([])),
    ).toBe("OoHOpBnrt8us7ph8DVnz5KrQs6UBqj_8MEACA0gWpjY=");
  });

  it("configured reviewed attributes contribute only when present on the item", () => {
    const base = baseStampable();
    const withConfig = reviewedConfig(["type"]);
    // absent attribute → identical to an empty attrs bag
    expect(computeItemStamp(base, withConfig)).toBe(
      computeItemStamp(base, reviewedConfig([])),
    );
    // present attribute → matches Doorstop unit vector (test_item.py)
    expect(
      computeItemStamp(baseStampable({ type: "functional" }), withConfig),
    ).toBe("MmcvtzB20PHv0IBhxpNtpZCa0CfYwHnPr3Jk8W-TRxk=");
  });

  it("matches Doorstop's embedded unit vectors (doorstop/core/tests/test_item.py)", () => {
    // item RQ001, empty text/ref, no links — extended attribute "attr"
    const cases: Array<[Record<string, unknown>, string]> = [
      [{ attr: 1 }, "0s4QQh2AZXSoZNYGcfybCGLHAgO4EWY9gxK_LVNiqOA="],
      [{ attr: "1" }, "GWlkpsRSzT_lgE4CNvE4wrUZZwM3iHKHOa6idcHUSUw="],
      [{ attr: null }, "e0qDli7ZJwhf161b_v7AdGNNl7xHx-bs28aFFk7aqT4="],
      [{ attr: "" }, "H70VgWPTH89Q9KfIJBfeilC7-wYAtWigxZ2iUcZ9j-8="],
      [{ attr: [] }, "qwUP7VgUbHWIdj-T2ZfGhROfJQwSHDhsC6WR9vUTk1U="],
      [{ attr: [null] }, "GHDRiY4C3twnXDTCqoCAD_iymfe892ZzQuYjuccFBT0="],
      [{ attr: [""] }, "Rfwtl2j56CdQLtE4b5StEa0ECVTqlOpABLdhEa1avyo="],
      [{ attr: [[]] }, "AXWIEp9CYI4UWzIw4NinvDrUFzQl_8rCL9B_PmGisYk="],
      [{ attr: [{}] }, "C5Bm5ej09zaJxbtbE9PIcno8M9lIBIC6sJOmNJkrJH8="],
      [{ attr: {} }, "5Yv0vWG2h5rAQt_1LujZuD9X6udWO52KVaSA5SJ3Emc="],
      [
        { attr: ["a", "b", ["c", { d: "e", f: ["g"] }]] },
        "JcCRKBgLLTOatY8OpAMabblP7Mu24JZRn3WgoXwjmSk=",
      ],
    ];
    for (const [attributes, stamp] of cases) {
      expect(
        computeItemStamp(baseStampable(attributes), reviewedConfig(["attr"])),
      ).toBe(stamp);
    }

    // two configured attributes — names sorted+deduped by the config layer,
    // so config order/duplicates are irrelevant (Doorstop's Document parses
    // attributes.reviewed as `sorted(set(...))`).  Doorstop's own unit test
    // assigned the RAW list to extended_reviewed (bypassing Document) and
    // pinned dMWAazlLoeZSwlD87nEwQtAFq32WQuX_Bd_8kehaKJg= for the reversed
    // order — a Python-side artifact; a config-driven document always sorts.
    const two = baseStampable({ type: "functional", "verification-method": "test" });
    expect(
      computeItemStamp(two, reviewedConfig(["type", "verification-method"])),
    ).toBe("TF_q0ofVwjaJI1RYu9jtDeSCm5gAQWIqsxpPxAW5D64=");
    expect(
      computeItemStamp(two, reviewedConfig(["verification-method", "type", "type"])),
    ).toBe("TF_q0ofVwjaJI1RYu9jtDeSCm5gAQWIqsxpPxAW5D64=");
    // the raw-order artifact vector for reference:
    // dMWAazlLoeZSwlD87nEwQtAFq32WQuX_Bd_8kehaKJg=
  });

  it("reproduces REQ006's fingerprint with reversed link file order (sorting)", () => {
    const re006 = itemsByUid.get("REQ006")!;
    const reversed: DoorstopStampableItem = {
      ...stampableOf(re006),
      links: [re006.links[1]!, re006.links[0]!],
    };
    expect(computeItemStamp(reversed, configOf(re006), true)).toBe(re006.reviewStamp);
    expect(computeItemStamp(reversed, configOf(re006), false)).toBe(re006.stamp);
  });
});

// --- schema-gap pins (extended reviewed attributes at the YAML 1.1/1.2 --------
// typing boundary) --------------------------------------------------------------

/** The port's expected serialization for each schema-gap scalar as the model
 *  chain delivers it (js-yaml's YAML 1.2 core-ish schema), stamped over the
 *  base empty item RQ001.  The fixture's `schemaGap` block pins REAL
 *  Doorstop's (PyYAML 1.1) serialization for the same lexemes; `parity`
 *  says whether the two coincide or the JS value is typeless where PyYAML
 *  kept the Python type (a documented divergence). */
const SCHEMA_GAP_CASES: Array<{ key: string; value: unknown; portConvert: string; portStamp: string }> = [
  // parity "equal" — the port reproduces Doorstop byte-for-byte
  { key: "int-5", value: 5, portConvert: "\\T<class 'int'>\\V5", portStamp: "mRIor-S-2b36s8-22eZkrjUEcJMb-8vznRGWzzKYxqI=" },
  { key: "str-date", value: "2024-01-01", portConvert: "\\T<class 'str'>\\V2024-01-01", portStamp: "aicMmDwLryYTaR4-TebhpCNbATtTa21ntWECikzq9iU=" },
  { key: "date", value: new Date("2024-01-01T00:00:00.000Z"), portConvert: "\\T<class 'datetime.date'>\\V2024-01-01", portStamp: "7F2rsDg3Jt_lY9ydPsWYPnl_twnICWD4yxSBSKbF2uU=" },
  {
    key: "datetime",
    value: new Date("2024-01-01T12:34:56.000Z"),
    portConvert: "\\T<class 'datetime.datetime'>\\V2024-01-01 12:34:56+00:00",
    portStamp: "3VqxfGWaintNxWtjcKVc8bOAVfTxUvvRO32_KQ_YX1Q=",
  },
  {
    key: "datetime-ms",
    value: new Date("2024-01-01T12:34:56.123Z"),
    portConvert: "\\T<class 'datetime.datetime'>\\V2024-01-01 12:34:56.123000+00:00",
    portStamp: "nMtLA3YrDJcLlPDM3_voFVpdLVWgNBaAqvdoG-bir0s=",
  },
  { key: "nan", value: NaN, portConvert: "\\T<class 'float'>\\Vnan", portStamp: "CZVveAFLdTTserXY3xP5hP_y790crCwBreB37_aetCU=" },
  { key: "inf", value: Infinity, portConvert: "\\T<class 'float'>\\Vinf", portStamp: "7U-fxVE7QdY88E5urYC1gg69uKyZAXuVw4434kuujDY=" },
  { key: "neg-inf", value: -Infinity, portConvert: "\\T<class 'float'>\\V-inf", portStamp: "_CGzAXBFRo9Ihxy6Sm_HzHab-jSbGK-sYx4OXMKrEb0=" },
  // parity "divergent" — the js-yaml value cannot carry the Python type
  { key: "float-5.0", value: 5, portConvert: "\\T<class 'int'>\\V5", portStamp: "mRIor-S-2b36s8-22eZkrjUEcJMb-8vznRGWzzKYxqI=" },
  { key: "float-1e2", value: 100, portConvert: "\\T<class 'int'>\\V100", portStamp: "QWAQH1-H4C19Ga47WZUyXGY6ohlDK5TgJJDPDYcT6jg=" },
  { key: "bool-yes", value: "yes", portConvert: "\\T<class 'str'>\\Vyes", portStamp: "r5otQHiPoYr6LVwEa3Vmf7CHgX9bw3NsdGJl-R9qru4=" },
  {
    key: "datetime-tz",
    value: new Date("2024-01-01T10:34:56.000Z"), // js-yaml UTC-normalizes `+02:00`
    portConvert: "\\T<class 'datetime.datetime'>\\V2024-01-01 10:34:56+00:00",
    portStamp: "Rp9tQuBCSH_BPKwLhLFBi0PzgmKuPQiYgnt_QKvqF8k=",
  },
];

describe("schema-gap pins — extended reviewed attributes at the YAML 1.1/1.2 typing boundary", () => {
  for (const entry of SCHEMA_GAP_CASES) {
    it(`pins '${entry.key}' against real Doorstop (${entry.portStamp})`, () => {
      const gap = fixtures.schemaGap.find((g) => g.key === entry.key);
      expect(gap, entry.key).toBeDefined();
      const convert = doorstopConvertToStr(entry.value);
      const stamp = computeItemStamp(baseStampable({ attr: entry.value }), reviewedConfig(["attr"]));
      // the port's own behavior is pinned hard, byte-for-byte
      expect(convert, entry.key).toBe(entry.portConvert);
      expect(stamp, entry.key).toBe(entry.portStamp);
      // and cross-checked against REAL Doorstop's serialization in the fixture
      if (gap!.parity === "equal") {
        expect(convert, entry.key).toBe(gap!.doorstopConvert);
        expect(stamp, entry.key).toBe(gap!.doorstopStamp);
      } else {
        // documented divergence — the JS value is typeless where PyYAML kept
        // the Python type; the pinned gap stays visible and any serializer
        // change here is a review event
        expect(convert, entry.key).not.toBe(gap!.doorstopConvert);
        expect(stamp, entry.key).not.toBe(gap!.doorstopStamp);
      }
    });
  }
});

// --- state chips + findings over the fixtures --------------------------------------

/** Doorstop message-prefix → plugin finding class (shared pin vocabulary). */
const CLASS_PREFIXES: ReadonlyArray<[string, "info" | "warning" | "error"]> = [
  ["linked to unknown item: ", "error"],
  ["linked to inactive item: ", "info"],
  ["linked to non-normative item: ", "warning"],
  ["suspect link: ", "warning"],
  ["no links to parent document: ", "warning"],
  ["no links from child document: ", "warning"],
  ["external reference not found: ", "error"],
  ["non-normative, but has links", "warning"],
  ["needs initial review", "info"],
  ["unreviewed changes", "warning"],
];

function classOf(message: string): { prefix: string; severity: "info" | "warning" | "error" } | null {
  for (const [prefix, severity] of CLASS_PREFIXES) {
    if (message.startsWith(prefix)) return { prefix, severity };
  }
  return null;
}

describe("computeItemStates — fixture chips, findings, counts", () => {
  const index = buildIndexFromFixtures();
  computeItemStates(index);
  const byUid = new Map(index.items.map((item) => [item.uid, item]));
  const findingsFor = (uid: string): Finding[] =>
    index.findings.filter((finding) => finding.uid === uid);

  it("annotates every item with the expected chips", () => {
    const expected: Record<string, string[]> = {
      REQ001: ["normative", "unreviewed"],
      REQ002: ["normative", "reviewed", "no-child-links"],
      REQ003: ["normative", "unreviewed", "suspect-link", "no-child-links"],
      REQ004: ["normative", "unreviewed", "no-child-links", "missing-reference"],
      REQ005: ["normative", "reviewed", "no-child-links"],
      REQ006: ["normative", "unreviewed", "no-child-links"],
      REQ007: ["non-normative", "unreviewed"],
      REQ008: ["normative", "inactive"],
      TST001: ["normative", "unreviewed", "suspect-link"],
      TST002: ["normative", "unreviewed", "no-links"],
      TST003: ["normative", "unreviewed"],
      TST004: ["normative", "unreviewed", "unknown-link"],
      TST005: ["normative", "unreviewed"],
      TST006: ["normative", "unreviewed"],
    };
    for (const fixture of fixtures.items) {
      expect(byUid.get(fixture.uid)!.stateKeys, fixture.uid).toEqual(expected[fixture.uid]);
    }
  });

  it("derives reviewed/unreviewed from the review stamp vs the stored value", () => {
    // REQ002/REQ005 were reviewed after their last change → "reviewed"
    expect(byUid.get("REQ002")!.stateKeys).toContain("reviewed");
    expect(byUid.get("REQ005")!.stateKeys).toContain("reviewed");
    // REQ001 was reviewed, then edited → its stored stamp went stale
    expect(byUid.get("REQ001")!.stateKeys).toContain("unreviewed");
    expect(findingsFor("REQ001").map((f) => [f.severity, f.message])).toContainEqual([
      "warning",
      "unreviewed changes",
    ]);
  });

  it("flags suspect links only when a recorded fingerprint differs from the current parent stamp", () => {
    // REQ003/TST001 recorded REQ001's pre-edit stamp → suspect
    expect(byUid.get("REQ003")!.stateKeys).toContain("suspect-link");
    expect(byUid.get("TST001")!.stateKeys).toContain("suspect-link");
    expect(findingsFor("TST001")).toContainEqual(
      expect.objectContaining({ severity: "warning", message: "suspect link: REQ001" }),
    );
    // REQ005 recorded REQ002's unchanged stamp, REQ006 recorded REQ005+TST001
    // stamps → not suspect, even though their records are non-null
    expect(byUid.get("REQ005")!.stateKeys).not.toContain("suspect-link");
    expect(byUid.get("REQ006")!.stateKeys).not.toContain("suspect-link");
    // null recordings (TST004/REQ007 unstamped links) are never suspect
    expect(byUid.get("TST004")!.stateKeys).not.toContain("suspect-link");
    expect(byUid.get("REQ007")!.stateKeys).not.toContain("suspect-link");
  });

  it("scopes no-child-links to child documents (childrenByUid + document tree)", () => {
    // REQ002/REQ005/REQ006: no item of a CHILD document links to them
    // (REQ006 links to REQ005, but REQ006 is in REQ, not a child doc)
    for (const uid of ["REQ002", "REQ004", "REQ005", "REQ006"]) {
      expect(byUid.get(uid)!.stateKeys).toContain("no-child-links");
    }
    // REQ001 has TST001 (child doc) linking to it; TST items have no child docs
    expect(byUid.get("REQ001")!.stateKeys).not.toContain("no-child-links");
    for (const uid of ["TST001", "TST002", "TST003"]) {
      expect(byUid.get(uid)!.stateKeys).not.toContain("no-child-links");
    }
    // non-normative items are exempt (Doorstop: CHECK_CHILD_LINKS + normative)
    expect(byUid.get("REQ007")!.stateKeys).not.toContain("no-child-links");
    expect(findingsFor("REQ002")).toContainEqual(
      expect.objectContaining({ severity: "warning", message: "no links from child document: TST" }),
    );
  });

  it("flags no-links for normative non-derived items with parent documents and no links", () => {
    expect(byUid.get("TST002")!.stateKeys).toContain("no-links");
    expect(findingsFor("TST002")).toContainEqual(
      expect.objectContaining({ severity: "warning", message: "no links to parent document: REQ" }),
    );
    // root-document items (no parent), derived items, and linked items are exempt
    expect(byUid.get("REQ001")!.stateKeys).not.toContain("no-links");
    expect(byUid.get("TST003")!.stateKeys).not.toContain("no-links");
    expect(byUid.get("TST001")!.stateKeys).not.toContain("no-links");
  });

  it("flags unknown-link for link targets missing from the index", () => {
    expect(byUid.get("TST004")!.stateKeys).toContain("unknown-link");
    expect(findingsFor("TST004")).toContainEqual(
      expect.objectContaining({ severity: "error", message: "linked to unknown item: REQ999" }),
    );
    // REQ007/REQ008 exist in the index (inactive/non-normative) → not unknown
    expect(byUid.get("TST005")!.stateKeys).not.toContain("unknown-link");
    expect(byUid.get("TST006")!.stateKeys).not.toContain("unknown-link");
  });

  it("flags missing references against knownFilePaths with error severity", () => {
    expect(byUid.get("REQ004")!.stateKeys).toContain("missing-reference");
    expect(findingsFor("REQ004")).toContainEqual({
      severity: "error",
      uid: "REQ004",
      message: "external reference not found: docs/refs/missing.md",
    });
    // REQ002's ref resolves to an indexed file → no chip
    expect(byUid.get("REQ002")!.stateKeys).not.toContain("missing-reference");
  });

  it("keeps inactive items to attribute mirrors only (Doorstop skips them)", () => {
    expect(byUid.get("REQ008")!.stateKeys).toEqual(["normative", "inactive"]);
    expect(findingsFor("REQ008")).toEqual([]);
  });

  it("aggregates the workspace counters", () => {
    expect(index.counts).toEqual({
      suspectLinks: 2, // REQ003, TST001
      unreviewedChanges: 11, // everything except REQ002, REQ005 (reviewed) and REQ008 (inactive)
      unknownLinks: 1, // TST004
      missingReferences: 1, // REQ004
      items: 14,
      documents: 2,
    });
  });

  it("reports ok=false while any error-severity finding exists", () => {
    expect(index.ok).toBe(false);
    expect(index.findings.some((finding) => finding.severity === "error")).toBe(true);
  });

  it("is idempotent (re-running changes nothing)", () => {
    const before = {
      chips: index.items.map((item) => [item.uid, [...item.stateKeys]] as const),
      findings: index.findings.map((finding) => ({ ...finding })),
      counts: { ...index.counts },
      ok: index.ok,
    };
    computeItemStates(index);
    expect(index.items.map((item) => [item.uid, [...item.stateKeys]])).toEqual(before.chips);
    expect(index.findings.map((finding) => ({ ...finding }))).toEqual(before.findings);
    expect({ ...index.counts, ok: index.ok }).toMatchObject(before.counts);
  });
});

describe("computeItemStates — severity model pinned by Doorstop's own issues", () => {
  const index = buildIndexFromFixtures();
  computeItemStates(index);

  it("plugin findings match the captured Doorstop severities (both directions)", () => {
    for (const fixture of fixtures.items) {
      const pluginFindings = index.findings.filter((finding) => finding.uid === fixture.uid);
      const doorstopClasses = new Set(
        fixture.issues
          .map((issue) => classOf(issue.message))
          .filter((entry): entry is NonNullable<typeof entry> => entry !== null),
      );
      // every plugin finding has a Doorstop counterpart with the same severity
      for (const finding of pluginFindings) {
        const cls = classOf(finding.message);
        expect(cls, `${fixture.uid}: ${finding.message}`).not.toBeNull();
        const doorstopIssue = fixture.issues.find((issue) => issue.message.startsWith(cls!.prefix));
        expect(doorstopIssue, `${fixture.uid}: ${finding.message}`).toBeDefined();
        expect(doorstopIssue!.severity.toUpperCase(), `${fixture.uid}: ${finding.message}`).toBe(
          finding.severity.toUpperCase(),
        );
      }
      // every Doorstop issue of a modeled class has a plugin finding with the
      // same severity ("no text" is the one unmodeled class — no chip for it)
      for (const issue of fixture.issues) {
        if (issue.message.startsWith("no text")) continue;
        const cls = classOf(issue.message);
        expect(cls, `${fixture.uid}: ${issue.message}`).not.toBeNull();
        const finding = pluginFindings.find((f) => f.message.startsWith(cls!.prefix));
        expect(finding, `${fixture.uid}: ${issue.message}`).toBeDefined();
        expect(finding!.severity.toUpperCase(), `${fixture.uid}: ${issue.message}`).toBe(
          issue.severity.toUpperCase(),
        );
      }
    }
  });
});

// --- integration with the model chain ----------------------------------------------

describe("integration with the model chain (parse → stamp → states)", () => {
  it("parses the fixture YAML and reproduces the fixture stamps byte-for-byte", () => {
    for (const fixture of fixtures.items) {
      const config = configOf(fixture);
      const result = parseDoorstopItem(fixture.path, fixture.yaml, config);
      expect(result.diagnostics).toEqual([]);
      const item = result.item;
      // normalized values agree with the fixture (root-relative, level, etc.)
      expect(item.uid).toBe(fixture.uid);
      expect(item.text).toBe(fixture.text);
      expect(item.ref).toBe(fixture.ref);
      expect(item.references).toEqual(referencesOf(fixture));
      expect(item.links).toEqual(fixture.links);
      expect(item.attributes).toEqual(fixture.attributes);
      expect(item.reviewed).toBe(fixture.reviewed);
      expect(item.active).toBe(fixture.active);
      expect(item.derived).toBe(fixture.derived);
      expect(item.normative).toBe(fixture.normative);
      // the parsed item stamps identically to Doorstop
      expect(computeItemStamp(item, config, false), fixture.uid).toBe(fixture.stamp);
      expect(computeItemStamp(item, config), fixture.uid).toBe(fixture.reviewStamp);
    }
  });

  it("builds the real index (buildDoorstopIndex) and computes state over it", () => {
    const itemsWithConfig = fixtures.items.map((fixture) => ({
      fixture,
      item: parseDoorstopItem(fixture.path, fixture.yaml, configOf(fixture)).item,
    }));
    const diagnostics: never[] = [];
    const index = buildDoorstopIndex(
      fixtureConfigs(),
      itemsWithConfig.map((entry) => entry.item),
      diagnostics,
      new Set(fixtures.knownFilePaths),
    );
    computeItemStates(index);

    // the model chain's index-time finding ("linked to unknown item: REQ999")
    // survives, and computeItemStates does not duplicate it
    const unknownFindings = index.findings.filter((finding) =>
      finding.message.startsWith("linked to unknown item: REQ999"),
    );
    expect(unknownFindings).toHaveLength(1);
    expect(index.byUid.get("TST004")!.stateKeys).toContain("unknown-link");

    // full chip set over the real index (spot checks + counts)
    const chips = new Map(index.items.map((item) => [item.uid, [...item.stateKeys]]));
    expect(chips.get("REQ001")).toEqual(["normative", "unreviewed"]);
    expect(chips.get("REQ002")).toEqual(["normative", "reviewed", "no-child-links"]);
    expect(chips.get("TST001")).toEqual(["normative", "unreviewed", "suspect-link"]);
    expect(chips.get("TST004")).toEqual(["normative", "unreviewed", "unknown-link"]);
    expect(index.counts).toEqual({
      suspectLinks: 2,
      unreviewedChanges: 11,
      unknownLinks: 1,
      missingReferences: 1,
      items: 14,
      documents: 2,
    });
    expect(index.ok).toBe(false);
  });
});

// --- synthetic state scenarios ------------------------------------------------------

function makeIndex(items: ItemRecord[]): DoorstopIndex {
  const byUid = new Map(items.map((item) => [item.uid, item]));
  const childrenByUid = new Map<string, ItemRecord[]>();
  for (const item of items) {
    for (const link of item.links) {
      const target = byUid.get(link.uid);
      if (target === undefined) continue;
      const children = childrenByUid.get(link.uid);
      if (children !== undefined) {
        children.push(item);
      } else {
        childrenByUid.set(link.uid, [item]);
      }
    }
  }
  return {
    documents: [],
    items,
    byUid,
    byPrefix: new Map(),
    parentLinksByUid: new Map(items.map((item) => [item.uid, item.links])),
    childrenByUid,
    findings: [],
    ok: true,
    diagnostics: [],
    knownFilePaths: new Set(),
    counts: {
      suspectLinks: 0,
      unreviewedChanges: 0,
      unknownLinks: 0,
      missingReferences: 0,
      items: items.length,
      documents: 0,
    },
  };
}

describe("computeItemStates — synthetic suspect-link scenario", () => {
  const reqConfig = makeDocument({ prefix: "REQ", directoryPath: "" });
  const tstConfig = makeDocument({ prefix: "TST", parentPrefix: "REQ", directoryPath: "tests" });
  const documents = [reqConfig, tstConfig];

  const v1Stamp = computeItemStamp(
    { uid: "REQ001", text: "v1", ref: "", links: [], attributes: {} },
    reqConfig,
    true,
  );

  const req001 = makeItem({
    uid: "REQ001",
    documentPrefix: "REQ",
    path: "REQ001.yml",
    text: "v1",
    reviewed: v1Stamp,
  });
  const tst001 = makeItem({
    uid: "TST001",
    documentPrefix: "TST",
    path: "tests/TST001.yml",
    text: "verify v1",
    links: [{ uid: "REQ001", fingerprint: v1Stamp }],
  });

  function indexForScenario(): DoorstopIndex {
    const index = makeIndex([req001, tst001]);
    index.documents = documents;
    index.byPrefix = new Map(documents.map((document) => [document.prefix, document]));
    return index;
  }

  it("sees no suspect links while the recorded fingerprint matches the parent stamp", () => {
    const index = indexForScenario();
    computeItemStates(index);
    expect(index.byUid.get("TST001")!.stateKeys).toContain("unreviewed");
    expect(index.byUid.get("TST001")!.stateKeys).not.toContain("suspect-link");
    expect(index.byUid.get("REQ001")!.stateKeys).toContain("reviewed");
    expect(index.counts.suspectLinks).toBe(0);
    expect(index.counts.unreviewedChanges).toBe(1);
  });

  it("flags the child suspect when the parent's text changes after recording", () => {
    req001.text = "v2"; // the shared object is mutated, exactly like a workspace edit
    const index = indexForScenario();
    computeItemStates(index);

    expect(index.byUid.get("TST001")!.stateKeys).toContain("suspect-link");
    expect(index.byUid.get("REQ001")!.stateKeys).toContain("unreviewed");
    expect(index.findings).toContainEqual(
      expect.objectContaining({ severity: "warning", uid: "TST001", message: "suspect link: REQ001" }),
    );
    expect(index.findings).toContainEqual(
      expect.objectContaining({ severity: "warning", uid: "REQ001", message: "unreviewed changes" }),
    );
    expect(index.counts.suspectLinks).toBe(1);
    expect(index.counts.unreviewedChanges).toBe(2);
    // and recomputation is stable
    const chips = index.items.map((item) => [...item.stateKeys]);
    computeItemStates(index);
    expect(index.items.map((item) => [...item.stateKeys])).toEqual(chips);
  });
});

describe("computeItemStates — re-running over a changed index drops stale findings", () => {
  it("removes a stale suspect-link finding once the recorded fingerprint matches again", () => {
    const reqConfig = makeDocument({ prefix: "REQ", directoryPath: "" });
    const tstConfig = makeDocument({ prefix: "TST", parentPrefix: "REQ", directoryPath: "tests" });
    const documents = [reqConfig, tstConfig];

    const v1Stamp = computeItemStamp(
      { uid: "REQ001", text: "v1", ref: "", links: [], attributes: {} },
      reqConfig,
      true,
    );
    const req001 = makeItem({
      uid: "REQ001",
      documentPrefix: "REQ",
      path: "REQ001.yml",
      text: "v1",
      reviewed: v1Stamp,
    });
    const tst001 = makeItem({
      uid: "TST001",
      documentPrefix: "TST",
      path: "tests/TST001.yml",
      text: "verify",
      links: [{ uid: "REQ001", fingerprint: v1Stamp }],
    });
    const index = makeIndex([req001, tst001]);
    index.documents = documents;
    index.byPrefix = new Map(documents.map((document) => [document.prefix, document]));

    computeItemStates(index);
    expect(index.findings.filter((f) => f.message.startsWith("suspect link"))).toHaveLength(0);

    // parent edited → the child's recorded fingerprint goes stale → suspect
    req001.text = "v2";
    computeItemStates(index);
    expect(index.findings).toContainEqual(
      expect.objectContaining({ severity: "warning", uid: "TST001", message: "suspect link: REQ001" }),
    );
    expect(index.counts.suspectLinks).toBe(1);

    // parent reverted on the SAME index object (no model-chain re-run) — the
    // stale suspect finding must NOT survive the re-run
    req001.text = "v1";
    computeItemStates(index);
    expect(index.findings.filter((f) => f.message.startsWith("suspect link"))).toHaveLength(0);
    expect(index.counts.suspectLinks).toBe(0);
  });

  it("removes a stale 'needs initial review' finding after the item is reviewed", () => {
    const reqConfig = makeDocument({ prefix: "REQ", directoryPath: "" });
    const documents = [reqConfig];
    const req001 = makeItem({
      uid: "REQ001",
      documentPrefix: "REQ",
      path: "REQ001.yml",
      text: "v1",
      reviewed: null,
    });
    const index = makeIndex([req001]);
    index.documents = documents;
    index.byPrefix = new Map(documents.map((document) => [document.prefix, document]));

    computeItemStates(index);
    expect(index.findings).toContainEqual(
      expect.objectContaining({ severity: "info", message: "needs initial review" }),
    );

    // `doorstop review` between runs updates ItemRecord.reviewed — the stale
    // info finding must disappear and the chip must flip to "reviewed"
    req001.reviewed = computeItemStamp(
      { uid: "REQ001", text: "v1", ref: "", links: [], attributes: {} },
      reqConfig,
      true,
    );
    computeItemStates(index);
    expect(index.findings.filter((f) => f.message.startsWith("needs initial review"))).toHaveLength(0);
    expect(index.byUid.get("REQ001")!.stateKeys).toContain("reviewed");
  });
});

describe("computeItemStates — childrenByUid child-document scoping", () => {
  it("ignores same-document links when deciding no-child-links", () => {
    const parentDoc = makeDocument({ prefix: "SYS", directoryPath: "sys" });
    const childDoc = makeDocument({ prefix: "TST", parentPrefix: "SYS", directoryPath: "tests" });
    const documents = [parentDoc, childDoc];

    const sys001 = makeItem({ uid: "SYS001", documentPrefix: "SYS", path: "sys/SYS001.yml", text: "parent" });
    const sys002 = makeItem({
      uid: "SYS002",
      documentPrefix: "SYS",
      path: "sys/SYS002.yml",
      text: "links to SYS001 from the SAME document",
      links: [{ uid: "SYS001", fingerprint: null }],
    });
    const tst001 = makeItem({
      uid: "TST001",
      documentPrefix: "TST",
      path: "tests/TST001.yml",
      text: "links to SYS002 from the child document",
      links: [{ uid: "SYS002", fingerprint: null }],
    });

    const index = makeIndex([sys001, sys002, tst001]);
    index.documents = documents;
    index.byPrefix = new Map(documents.map((document) => [document.prefix, document]));
    computeItemStates(index);

    // SYS001: only same-document links → still no child links
    expect(index.byUid.get("SYS001")!.stateKeys).toContain("no-child-links");
    // SYS002: has a child-document (TST) link → no chip
    expect(index.byUid.get("SYS002")!.stateKeys).not.toContain("no-child-links");
  });
});